apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-hello-ingress
  namespace: java-hello-world
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: public
  rules:
    - host: java-hello.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
