apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: csharp-hello-logger-ingress
  namespace: csharp-hello-world-logger
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: public
  rules:
    - host: csharp-hello-logger.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
