apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-opensearch-single-rest
  namespace: integration-clients
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-opensearch-single-rest
  template:
    metadata:
      labels:
        app: nodejs-opensearch-single-rest
    spec:
      containers:
        - name: app
          image: prototype/nodejs-opensearch-single-rest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: OPENSEARCH_URL
              value: "http://opensearch-single.integration-opensearch-single.svc.cluster.local:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-opensearch-single-rest
  namespace: integration-clients
spec:
  selector:
    app: nodejs-opensearch-single-rest
  ports:
    - name: http
      port: 8080
      targetPort: 8080
