services:
  web:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: prototype/csharp-hello-world-logger:latest
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
    restart: unless-stopped
