receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

  filelog:
    include: [/var/log/demo-app/*.log]
    start_at: beginning

processors:
  batch:

exporters:
  otlphttp/tempo:
    endpoint: http://tempo:4318

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo]

    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [loki]
